[package]
name = "mattermost-chatgpt-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.94"
tokio-tungstenite = "*"
futures = "0.3.26"
tokio = { version = "1.26.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
tracing = "0.1.35"
tracing-subscriber = {version = "0.3.14", features = ["env-filter"]}
tracing-appender = "0.2.2"
chrono = "0.4.19"

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { n = "0.10.37", features = ["vendored"] }

[[bin]]
name = "app"
path = "src/main.rs"

